<?php

function notify($to, $data) {
    $api_key = "AAAA1AmLWwE:APA91bE3870HoW0g6fwQuCOINSw3HExB5ibRQRDJSA8Zqj5KcZIV57kSxo3lNaH5tpWatD_doF0pCePpMKE28d5y7C4B0vHBmWD_LDygNgtaJC4SS03b7KfdXO9UQ0v474CuGvNOeueU";
    $url = "https://fcm.googleapis.com/fcm/send";
    $fields = json_encode(array('to' => $to, 'notification' => $data));

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();

    curl_setopt($ch, CURLOPT_URL, $url);
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_POST, 1);
    curl_setopt($ch, CURLOPT_POSTFIELDS, ($fields));

    $headers = array();
    $headers[] = 'Authorization: key ='.$api_key;
    $headers[] = 'Content-Type: application/json';
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);

    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo 'Error:' . curl_error($ch);
    }
    curl_close($ch);
}
?>